// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Secure_Api_Jwt.Models
{
    public partial class Hotel_RESERVATIONContext : DbContext
    {
     

        public Hotel_RESERVATIONContext(DbContextOptions<Hotel_RESERVATIONContext> options)
            : base(options)
        {
        }

        public virtual DbSet<reservation> reservations { get; set; }

      

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<reservation>(entity =>
            {
                entity.Property(e => e.card_cvc).IsFixedLength();

                entity.Property(e => e.card_type).IsFixedLength();

                entity.Property(e => e.payment_type).IsFixedLength();

                entity.Property(e => e.room_floor).IsFixedLength();

                entity.Property(e => e.room_number).IsFixedLength();

                entity.Property(e => e.room_type).IsFixedLength();

                entity.Property(e => e.zip_code).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}